name: Selenium CI with Gradle

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Grant permission to execute Gradle
      run: chmod +x gradlew

    - name: Run Selenium Tests with Gradle
      run: ./gradlew test

    - name: Upload Test Reports
      if: always()  # Upload even if tests fail
      uses: actions/upload-artifact@v3
      with:
        name: test-reports
        path: build/reports/tests/test/
